version: '3'
services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=versla
      - PORT=8080
      - GIN_MODE=release
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: always

  db:
    image: bitnami/mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: versla
    ports:
      - 3307:3306
    restart: always
